<?php
/*
 *** DON'T EDIT THIS FILE! ***
 *
 * This file was automatically generated by the Lime parser generator.
 * The real source code you should be looking at is in one or more
 * grammar files in the Lime format.
 *
 * THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
 * file that your error happened, because there are enough comments to
 * help you debug your grammar.

 * If you ignore this warning, you're shooting yourself in the brain,
 * not the foot.
 */

namespace JavanileDefine;

class DefineParser extends \Genesis\Lime\LimeParser {
  public $qi = 0;
  public $i = array(
    array(
      'define_stmt' => 's 1',
      'DEFINE' => 's 2',
      'stmt' => 's 8',
      "'start'" => "a 'start'"
    ),
    array(
      '#' => 'r 0'
    ),
    array(
      'concept' => 's 3',
      'CONCEPT' => 's 7'
    ),
    array(
      'WITH' => 's 4',
      '#' => 'r 1'
    ),
    array(
      'concept_list' => 's 5',
      'concept' => 's 6',
      'CONCEPT' => 's 7'
    ),
    array(
      '#' => 'r 2'
    ),
    array(
      '#' => 'r 3'
    ),
    array(
      'WITH' => 'r 4',
      '#' => 'r 4'
    ),
    array(
      '#' => 'r 5'
    )
  );
  public $d = array(

  );
  public $errors = array();
  function reduce_0_stmt_1($tokens, &$result) {
    // (0) stmt :=  define_stmt
    $result = reset($tokens);
  }

  function reduce_1_define_stmt_1($tokens, &$result) {
    // (1) define_stmt :=  DEFINE  concept
    $result = reset($tokens);
  }

  function reduce_2_define_stmt_2($tokens, &$result) {
    // (2) define_stmt :=  DEFINE  concept  WITH  concept_list
    $result = reset($tokens);
  }

  function reduce_3_concept_list_1($tokens, &$result) {
    // (3) concept_list :=  concept
    $result = reset($tokens);
  }

  function reduce_4_concept_1($tokens, &$result) {
    // (4) concept :=  CONCEPT
    $result = reset($tokens);
  }

  function reduce_5_start_1($tokens, &$result) {
    // (5) 'start' :=  stmt
    $result = reset($tokens);
  }

  public $method = array(
    'reduce_0_stmt_1',
    'reduce_1_define_stmt_1',
    'reduce_2_define_stmt_2',
    'reduce_3_concept_list_1',
    'reduce_4_concept_1',
    'reduce_5_start_1'
  );
  public $a = array(
    array(
      'symbol' => 'stmt',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'define_stmt',
      'len' => 2,
      'replace' => true
    ),
    array(
      'symbol' => 'define_stmt',
      'len' => 4,
      'replace' => true
    ),
    array(
      'symbol' => 'concept_list',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'concept',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => "'start'",
      'len' => 1,
      'replace' => true
    )
  );
}

// Time: 0.0091919898986816 seconds
// Memory: 1346624 bytes
