<?php
/*
 *** DON'T EDIT THIS FILE! ***
 *
 * This file was automatically generated by the Lime parser generator.
 * The real source code you should be looking at is in one or more
 * grammar files in the Lime format.
 *
 * THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
 * file that your error happened, because there are enough comments to
 * help you debug your grammar.

 * If you ignore this warning, you're shooting yourself in the brain,
 * not the foot.
 */

namespace JavanileDefine;

class DefineParser extends \Genesis\Lime\LimeParser {
  public $qi = 0;
  public $i = array(
    array(
      'a' => 's 1',
      'b' => 's 2',
      'stmt' => 's 3',
      "'start'" => "a 'start'"
    ),
    array(
      '#' => 'r 0'
    ),
    array(
      '#' => 'r 1'
    ),
    array(
      '#' => 'r 2'
    )
  );
  public $d = array(

  );
  public $errors = array();
  function reduce_0_stmt_1($tokens, &$result) {
    // (0) stmt :=  a
    $result = reset($tokens);
  }

  function reduce_1_stmt_2($tokens, &$result) {
    // (1) stmt :=  b
    $result = reset($tokens);
  }

  function reduce_2_start_1($tokens, &$result) {
    // (2) 'start' :=  stmt
    $result = reset($tokens);
  }

  public $method = array(
    'reduce_0_stmt_1',
    'reduce_1_stmt_2',
    'reduce_2_start_1'
  );
  public $a = array(
    array(
      'symbol' => 'stmt',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'stmt',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => "'start'",
      'len' => 1,
      'replace' => true
    )
  );
}

// Time: 0.0055148601531982 seconds
// Memory: 1346624 bytes
