<?php
/*
 *** DON'T EDIT THIS FILE! ***
 *
 * This file was automatically generated by the Lime parser generator.
 * The real source code you should be looking at is in one or more
 * grammar files in the Lime format.
 *
 * THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
 * file that your error happened, because there are enough comments to
 * help you debug your grammar.

 * If you ignore this warning, you're shooting yourself in the brain,
 * not the foot.
 */

namespace JavanileDefine;

class GrammarParser extends \Genesis\Lime\LimeParser {
  public $qi = 0;
  public $i = array(
    array(
      'loads_stmt' => 's 1',
      'define_stmt' => 's 2',
      'DEFINE' => 's 3',
      'start_stmt' => 's 10',
      "'start'" => "a 'start'"
    ),
    array(
      '#' => 'r 0'
    ),
    array(
      '#' => 'r 1'
    ),
    array(
      'concept' => 's 4',
      'CONCEPT' => 's 9'
    ),
    array(
      'WITH' => 's 5',
      '#' => 'r 2'
    ),
    array(
      'concept_list' => 's 6',
      "'concept_list'4" => 's 7',
      'CONCEPT' => 'r 4'
    ),
    array(
      '#' => 'r 3'
    ),
    array(
      'concept' => 's 8',
      'CONCEPT' => 's 9'
    ),
    array(
      '#' => 'r 5'
    ),
    array(
      'WITH' => 'r 6',
      '#' => 'r 6'
    ),
    array(
      '#' => 'r 7'
    )
  );
  public $d = array(

  );
  public $errors = array();
  function reduce_0_start_stmt_1($tokens, &$result) {
    // (0) start_stmt :=  loads_stmt
    $result = reset($tokens);
  }

  function reduce_1_loads_stmt_1($tokens, &$result) {
    // (1) loads_stmt :=  define_stmt
    $result = reset($tokens);
  }

  function reduce_2_define_stmt_1($tokens, &$result) {
    // (2) define_stmt :=  DEFINE  concept
    $result = reset($tokens);
    $this->define($tokens[1]);
  }

  function reduce_3_define_stmt_2($tokens, &$result) {
    // (3) define_stmt :=  DEFINE  concept  WITH  concept_list
    $result = reset($tokens);
    $this->define($tokens[1], $tokens[3]);
  }

  function reduce_4_concept_list4_1($tokens, &$result) {
    // (4) 'concept_list'4 :=  ε
    $result = reset($tokens);
    $result = [];
  }

  function reduce_5_concept_list_1($tokens, &$result) {
    // (5) concept_list :=  'concept_list'4  concept
    $result = reset($tokens);
    $result[] = $tokens[1];
  }

  function reduce_6_concept_1($tokens, &$result) {
    // (6) concept :=  CONCEPT
    $result = reset($tokens);
  }

  function reduce_7_start_1($tokens, &$result) {
    // (7) 'start' :=  start_stmt
    $result = reset($tokens);
  }

  public $method = array(
    'reduce_0_start_stmt_1',
    'reduce_1_loads_stmt_1',
    'reduce_2_define_stmt_1',
    'reduce_3_define_stmt_2',
    'reduce_4_concept_list4_1',
    'reduce_5_concept_list_1',
    'reduce_6_concept_1',
    'reduce_7_start_1'
  );
  public $a = array(
    array(
      'symbol' => 'start_stmt',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'loads_stmt',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'define_stmt',
      'len' => 2,
      'replace' => true
    ),
    array(
      'symbol' => 'define_stmt',
      'len' => 4,
      'replace' => true
    ),
    array(
      'symbol' => "'concept_list'4",
      'len' => 0,
      'replace' => false
    ),
    array(
      'symbol' => 'concept_list',
      'len' => 2,
      'replace' => true
    ),
    array(
      'symbol' => 'concept',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => "'start'",
      'len' => 1,
      'replace' => true
    )
  );
}

// Time: 0.0095400810241699 seconds
// Memory: 1346624 bytes
