<?php
/*
 *** DON'T EDIT THIS FILE! ***
 *
 * This file was automatically generated by the Lime parser generator.
 * The real source code you should be looking at is in one or more
 * grammar files in the Lime format.
 *
 * THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
 * file that your error happened, because there are enough comments to
 * help you debug your grammar.

 * If you ignore this warning, you're shooting yourself in the brain,
 * not the foot.
 */

namespace Javanile\Define;

class GrammarParser extends \Genesis\Lime\LimeParser {
  public $qi = 0;
  public $i = array(
    array(
      'loads_stmt' => 's 1',
      'define_stmt' => 's 12',
      'DEFINE' => 's 3',
      "'define_stmt'4" => 's 7',
      'start_stmt' => 's 13',
      "'start'" => "a 'start'"
    ),
    array(
      'define_stmt' => 's 2',
      'DEFINE' => 's 3',
      "'define_stmt'4" => 's 7',
      '#' => 'r 0'
    ),
    array(
      'DEFINE' => 'r 2',
      '#' => 'r 2'
    ),
    array(
      'concept' => 's 4',
      'LITERAL' => 's 5',
      'PATH' => 's 6'
    ),
    array(
      'DEFINE' => 'r 3',
      '#' => 'r 3',
      'WITH' => 'r 4'
    ),
    array(
      'DEFINE' => 'r 8',
      'WITH' => 'r 8',
      'LITERAL' => 'r 8',
      'PATH' => 'r 8',
      '#' => 'r 8'
    ),
    array(
      'DEFINE' => 'r 9',
      'WITH' => 'r 9',
      'LITERAL' => 'r 9',
      'PATH' => 'r 9',
      '#' => 'r 9'
    ),
    array(
      'WITH' => 's 8'
    ),
    array(
      'concept_list' => 's 9',
      'concept' => 's 11',
      'LITERAL' => 's 5',
      'PATH' => 's 6'
    ),
    array(
      'concept' => 's 10',
      'LITERAL' => 's 5',
      'PATH' => 's 6',
      'DEFINE' => 'r 5',
      '#' => 'r 5'
    ),
    array(
      'LITERAL' => 'r 7',
      'PATH' => 'r 7',
      'DEFINE' => 'r 7',
      '#' => 'r 7'
    ),
    array(
      'LITERAL' => 'r 6',
      'PATH' => 'r 6',
      'DEFINE' => 'r 6',
      '#' => 'r 6'
    ),
    array(
      'DEFINE' => 'r 1',
      '#' => 'r 1'
    ),
    array(
      '#' => 'r 10'
    )
  );
  public $d = array(

  );
  public $errors = array();
  function reduce_0_start_stmt_1($tokens, &$result) {
    // (0) start_stmt :=  loads_stmt
    $result = reset($tokens);
  }

  function reduce_1_loads_stmt_1($tokens, &$result) {
    // (1) loads_stmt :=  define_stmt
    $result = reset($tokens);
  }

  function reduce_2_loads_stmt_2($tokens, &$result) {
    // (2) loads_stmt :=  loads_stmt  define_stmt
    $result = reset($tokens);
  }

  function reduce_3_define_stmt_1($tokens, &$result) {
    // (3) define_stmt :=  DEFINE  concept
    $result = reset($tokens);
    $this->define($tokens[1]);
  }

  function reduce_4_define_stmt4_1($tokens, &$result) {
    // (4) 'define_stmt'4 :=  DEFINE  concept
    $result = reset($tokens);
    $this->define($tokens[1]);
  }

  function reduce_5_define_stmt_2($tokens, &$result) {
    // (5) define_stmt :=  'define_stmt'4  WITH  concept_list
    $result = reset($tokens);
    $this->relate($tokens[1], $tokens[4]);
  }

  function reduce_6_concept_list_1($tokens, &$result) {
    // (6) concept_list :=  concept
    $result = reset($tokens);
    $result = $this->append([], $tokens[0]);
  }

  function reduce_7_concept_list_2($tokens, &$result) {
    // (7) concept_list :=  concept_list  concept
    $result = reset($tokens);
    $result = $this->append($tokens[0], $tokens[1]);
  }

  function reduce_8_concept_1($tokens, &$result) {
    // (8) concept :=  LITERAL
    $result = reset($tokens);
  }

  function reduce_9_concept_2($tokens, &$result) {
    // (9) concept :=  PATH
    $result = reset($tokens);
  }

  function reduce_10_start_1($tokens, &$result) {
    // (10) 'start' :=  start_stmt
    $result = reset($tokens);
  }

  public $method = array(
    'reduce_0_start_stmt_1',
    'reduce_1_loads_stmt_1',
    'reduce_2_loads_stmt_2',
    'reduce_3_define_stmt_1',
    'reduce_4_define_stmt4_1',
    'reduce_5_define_stmt_2',
    'reduce_6_concept_list_1',
    'reduce_7_concept_list_2',
    'reduce_8_concept_1',
    'reduce_9_concept_2',
    'reduce_10_start_1'
  );
  public $a = array(
    array(
      'symbol' => 'start_stmt',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'loads_stmt',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'loads_stmt',
      'len' => 2,
      'replace' => true
    ),
    array(
      'symbol' => 'define_stmt',
      'len' => 2,
      'replace' => true
    ),
    array(
      'symbol' => "'define_stmt'4",
      'len' => 2,
      'replace' => false
    ),
    array(
      'symbol' => 'define_stmt',
      'len' => 5,
      'replace' => true
    ),
    array(
      'symbol' => 'concept_list',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'concept_list',
      'len' => 2,
      'replace' => true
    ),
    array(
      'symbol' => 'concept',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => 'concept',
      'len' => 1,
      'replace' => true
    ),
    array(
      'symbol' => "'start'",
      'len' => 1,
      'replace' => true
    )
  );
}

// Time: 0.010401964187622 seconds
// Memory: 1352232 bytes
